### ISSUE TITLE
Mod Name

### ISSUE THREAD

**Issue by tsetsoo0** [pnk2u/More-Grindstone-Variants#1]
I don't really know how to describe this, but instead of the name being 'MoreGrindstoneVariants' or something like that, it just says '$mod-name'. I don't have anything else to say, so please see the issue. Thank you !
![image_2024-10-26_204920313](https://github.com/user-attachments/assets/0e22db4a-8aed-4c47-850b-6956068f14d6)

**Comment by pnk2u** [comment]
Thanks for letting me know about this. I think I know what's causing this, but just so I can test it, what is this program called you're using in the screenshot?
Oh, and are you using other mods of mine that don't have that issue?

**Comment by pnk2u** [comment]
You can also try downloading the version again as I now uploaded the correct file that I would hope should not produce this error.

**Comment by tsetsoo0** [comment]
i am using UltimMC. anyways, thanks for fixing the issue! its working now =) have a good night/day!
